
import { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import MobileNavbar from "@/components/mobile-navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="fr"
    >
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/xlr5bqj.css" />
      </head> 
      <body
        className={`antialiased`}
      >
        <Providers>
          {children}
          <MobileNavbar />
        </Providers>
      </body>
    </html>
  );
}
